### ISSUE TITLE
about raycast

### ISSUE THREAD

**Issue by lo-th** [fabmax/physx-js-webidl#10]
Hi me again about raycast 

standard init for ray is 
```
const rayBuffer = new PhysX.PxRaycastBuffer10()
const rayFlags = new PhysX.PxHitFlags( PhysX._emscripten_enum_PxHitFlagEnum_eDEFAULT() );
const rayFilter = new PhysX.PxQueryFilterData();
```
after on step 
`let hit = root.scene.raycast( v1, v2, distance, rayBuffer, rayFlags, rayFilter )`

hit work is return good true or false
but rayBuffer.block not return good position normal and actor ?
if you have idea, thank's

**Comment by fabmax** [comment]
I think with `eDEFAULT` flags the raycast reports multiple hits instead of a single blocking one (although according to the [doc](https://gameworksdocs.nvidia.com/PhysX/4.1/documentation/physxapi/files/structPxHitFlag.html#a44c173f6ddf0522ffbd8fa3c585e6b64a639d134a27861f74e3721dbd7be65bbc) it should not) 

You should be able to iterate over the result in a loop (until `rayBuffer.getNbAnyHits()`) and take the nearest from `rayBuffer.getAnyHit()`. Alternatively you can try to play around with the flags but I don't know if that makes a difference.

**Comment by lo-th** [comment]
yes is perfect many thank's
```
let r = rayBuffer.getAnyHit()
r.position, r.normal , r.actor are good 
```

and rayBuffer.getNbAnyHits() return 1 with default
