### ISSUE TITLE
Retrieving userData

### ISSUE THREAD

**Issue by krakn-dev** [fabmax/physx-js-webidl#31]
**Hey fabmax**, i have been banging my head and yet haven't been able to retrieve the data i put inside the `userData` attribute, it seems to return a pointer(VoidPtr), but i see there is no way to dereference it.
I appreciate your help in advance.

**Comment by fabmax** [comment]
Ah yes I don't think there's an easy way to use this in javascript unfortunately...

The problem is that the `userData` field indeed is a void pointer so you can only put a reference to another native object there. A relatively simple workaround is to use a dictionary instead: You can use the memory address of any native object as key and map that to any object you like:

```javascript
let userDataMap = { }

// on creating an actor
userDataMap[someActor.ptr] = "some arbirtray user data";

// retrieve user data sometime later, e.g. inside a callback function
let userData = userDataMap[actor.ptr]
```

The `ptr` field contains the native memory address which is unique and doesn't change for the entire lifetime of a native object.

**Comment by krakn-dev** [comment]
that's a clever a approach. i was looking to insert an unique id inside the actor anyways, so no `userData` required in my case, i hope these issues are useful for anyone considering this library, have a very nice day, fabmax.

**Comment by Eshku** [comment]
Old post, but might be useful for future people researching on userData storage and retrieval.

There is a little hack we can use to store data without userData.

const userData = {
			id: this.id,
			stats: stats
		}



actor.setName(JSON.stringify(playerData));

const retrievedInfo = JSON.parse(actor.getName())

That approach would be more straight forward if we have EntityManager or some structure which already stores entity map and can getEntityByID. (Which we should have tbh).


I did not test how much info it allows us to store, tested to 100 pairs.
